#!/usr/bin/env bash
# Generated by pivota-spec init-dev-server
# Catalog entry: react-vite
# Generator version: init-dev-server@1
#
# Edits ABOVE the END PIVOTA PREAMBLE marker are reset on regen.
# Edits BELOW the marker are preserved on regen.
#
# Why these choices (decision-trace; do not delete):
#   - `set -euo pipefail` not just `-e` — RESEARCH.md Pitfall 4 (silent pipe failures).
#   - `sha256sum` for lockfile hashing — RESEARCH.md "Don't hand-roll" (universal
#     coreutils, no extra dep vs blake3 / git hash-object / md5sum).
#   - Backoff 1s / 2s / 4s — Claude's Discretion per CONTEXT.md (small base, predictable).
#   - Log destination `/tmp/pivota-dev.log` — Open Question #4 resolved (always
#     writable inside Daytona sandboxes; matches existing convention).
#   - Lockfile-sentinel skip combined with INSTALL_PRESENCE_CHECK — RESEARCH.md
#     Pitfall 6 (sentinel survives reboots but install output dirs may not on
#     fresh tmpfs; never skip on a clean directory).
#   - Retry exits with INNER command's last exit code (not a fixed 1) so callers
#     can disambiguate failures from the wrapper.
#   - Multi-process (bash trap + wait -n) used because this project runs both
#     a Vite frontend (port 5173) and an Express/tsx backend (port 3000) that
#     Vite proxies. concurrently (the project's npm dev script) is replaced with
#     the framework-canonical supervision pattern (catalog/README.md anti-pattern 2).

set -euo pipefail

# === Bash version guard (RESEARCH.md Pitfall 8) ===
# `wait -n` (used by the multi-process variant) requires bash >= 4.3.
# Fail fast with a clear message; do not silently degrade.
if (( BASH_VERSINFO[0] < 4 )) || { (( BASH_VERSINFO[0] == 4 )) && (( BASH_VERSINFO[1] < 3 )); }; then
  echo "[pivota] bash 4.3+ required for 'wait -n'; found ${BASH_VERSION}" >&2
  exit 127
fi

# === D-11.4: tee stdout/stderr to /tmp/pivota-dev.log AND pass through ===
mkdir -p /tmp
exec > >(tee -a /tmp/pivota-dev.log) 2>&1
echo "[pivota] $(date -Iseconds) start-dev.sh begin (catalog: react-vite)"

# === D-11.1 + D-11.2: per-stack 0.0.0.0 binding + host allowlist relaxation ===
export HOST=0.0.0.0
# NOTE: Vite does NOT honor HOST as a server bind var; it is set here only for
# downstream tooling that may read it (Next-style apps importing utilities,
# scripts that branch on $HOST, etc.).
# The actual Vite bind comes from the --host 0.0.0.0 CLI flag in the per-process cmd.
#
# VITE_HOST and VITE_ALLOWED_HOSTS do NOT exist as Vite env vars
# (CITED: github.com/vitejs/vite issue #19273, vite.dev/config/server-options).
# This is the RESEARCH.md Pitfall 1 trap — the CLI flag is canonical.
#
# Express backend port (must match vite.config.ts proxy target of port 3000).
export PORT="${PORT:-3000}"

# === D-11.3: .env.example -> .env seed (platform-injection-safe) ===
if [[ ! -f .env && -f .env.example ]]; then
  echo "[pivota] seeding .env from .env.example (preserving platform-injected vars)"
  while IFS= read -r line || [[ -n "$line" ]]; do
    trimmed="${line#"${line%%[![:space:]]*}"}"   # left-trim for the test only
    if [[ "$trimmed" == \#* || -z "$trimmed" || "$trimmed" != *"="* ]]; then
      printf '%s\n' "$line"; continue            # keep comments / blanks / non-assignments
    fi
    key="${trimmed#export }"; key="${key%%=*}"; key="${key//[[:space:]]/}"
    if [[ -n "${!key+x}" ]]; then
      printf '# [pivota] %s omitted — provided by platform environment\n' "$key"
    else
      printf '%s\n' "$line"
    fi
  done < .env.example > .env
fi

# === Pre-exec snippet: write vite.config.pivota.ts overlay (allowedHosts) ===
if [[ -f vite.config.ts && ! -f vite.config.pivota.ts ]]; then
  if ! grep -q "allowedHosts" vite.config.ts 2>/dev/null; then
    cat > vite.config.pivota.ts <<'VITE_EOF'
// Auto-generated by pivota init-dev-server. Extends user's vite.config.ts at runtime
// to set server.allowedHosts = true (sandbox preview embedding) and host=true (so
// the dev server binds 0.0.0.0). Remove this file if you set allowedHosts yourself.
import { defineConfig, mergeConfig } from 'vite';
import userConfig from './vite.config';
export default defineConfig((env) => mergeConfig(
  typeof userConfig === 'function' ? userConfig(env) : userConfig,
  { server: { host: true, allowedHosts: true, strictPort: true } }
));
VITE_EOF
    echo "[pivota] wrote vite.config.pivota.ts (allowedHosts overlay)"
  fi
fi

# === D-12: idempotent install via lockfile hash + presence check ===
SENTINEL="/tmp/pivota-setup-sentinel"
LOCK_FILE_PATH="package-lock.json"
INSTALL_PRESENCE_CHECK="node_modules"
INSTALL_CMD='npm ci || npm install'

run_install() {
  echo "[pivota] running install: $INSTALL_CMD"
  bash -c "$INSTALL_CMD"
}

if [[ -n "$LOCK_FILE_PATH" && -f "$LOCK_FILE_PATH" ]]; then
  CURRENT_HASH=$(sha256sum "$LOCK_FILE_PATH" | cut -d' ' -f1)
  PREVIOUS_HASH=$(cat "$SENTINEL" 2>/dev/null || echo "")

  PRESENCE_OK=1
  if [[ -n "$INSTALL_PRESENCE_CHECK" && ! -e "$INSTALL_PRESENCE_CHECK" ]]; then
    PRESENCE_OK=0
  fi

  if [[ "$CURRENT_HASH" == "$PREVIOUS_HASH" && "$PRESENCE_OK" == "1" ]]; then
    echo "[pivota] lockfile unchanged AND install output present; skipping install"
  else
    if [[ "$PRESENCE_OK" == "0" ]]; then
      echo "[pivota] install output ($INSTALL_PRESENCE_CHECK) missing; install required"
    else
      echo "[pivota] lockfile changed (or first boot); install required"
    fi
    run_install
    echo "$CURRENT_HASH" > "$SENTINEL"
  fi
elif [[ -n "$INSTALL_CMD" ]]; then
  if [[ ! -f "$SENTINEL" ]]; then
    run_install
    touch "$SENTINEL"
  fi
fi

# === Multi-process supervision: Vite frontend + Express/tsx backend ===
# bash trap + wait -n per multi-process-template.md (NEVER concurrently/pm2/supervisord).
# The project's npm run dev uses `concurrently` — replaced here with the framework-
# canonical pattern so signal handling and sandbox teardown work correctly.

shutdown() {
  echo "[pivota] shutting down children"
  kill -TERM "${PIDS[@]}" 2>/dev/null || true
  # Brief grace, then SIGKILL stragglers (RESEARCH.md Pitfall 3: npm SIGTERM)
  sleep 2
  kill -KILL "${PIDS[@]}" 2>/dev/null || true
  wait
}
trap shutdown SIGTERM SIGINT EXIT

declare -a PIDS=()

# Process 1: Express/tsx backend (port 3000 — Vite proxy target)
(
  cd '.' \
    && export PORT="${PORT:-3000}" \
    && exec bash -c 'npx tsx server.ts'
) 2>&1 | sed 's/^/[backend] /' &
PIDS+=($!)

# Process 2: Vite frontend (port 5173 — with allowedHosts overlay)
(
  cd '.' \
    && export HOST=0.0.0.0 \
    && exec bash -c 'npm run dev -- --config vite.config.pivota.ts --host 0.0.0.0 --strictPort 2>/dev/null || npm run dev -- --host 0.0.0.0 --strictPort'
) 2>&1 | sed 's/^/[frontend] /' &
PIDS+=($!)

# Wait for ANY child to exit; if one dies, the trap tears down siblings.
wait -n
EXIT_CODE=$?
shutdown
exit "$EXIT_CODE"

# Unreachable, but keep for analyzer happiness
exit 1
# === END PIVOTA PREAMBLE ===
# Below this marker, projects may add custom shutdown / setup logic.
# This region is PRESERVED across regenerations (plan 06's regen logic detects
# the marker and re-appends user content verbatim after re-emitting the preamble).
