#!/usr/bin/env bash
# Generated by pivota-spec init-dev-server
# Catalog entry: agent (react-vite + express multi-process)
# Generator version: init-dev-server@1
#
# Edits ABOVE the END PIVOTA PREAMBLE marker are reset on regen.
# Edits BELOW the marker are preserved on regen.
#
# Why these choices (decision-trace; do not delete):
#   - `set -euo pipefail` not just `-e` — RESEARCH.md Pitfall 4 (silent pipe failures).
#   - `sha256sum` for lockfile hashing — RESEARCH.md "Don't hand-roll" (universal
#     coreutils, no extra dep vs blake3 / git hash-object / md5sum).
#   - Backoff 1s / 2s / 4s — Claude's Discretion per CONTEXT.md (small base, predictable).
#   - Log destination `/tmp/pivota-dev.log` — Open Question #4 resolved (always
#     writable inside Daytona sandboxes; matches existing convention).
#   - Lockfile-sentinel skip combined with INSTALL_PRESENCE_CHECK — RESEARCH.md
#     Pitfall 6 (sentinel survives reboots but install output dirs may not on
#     fresh tmpfs; never skip on a clean directory).
#   - Multi-process: Express backend (port 3000) + Vite frontend (port 5173).
#     Uses bash trap + wait -n per RESEARCH.md Pattern 3. NOT concurrently/pm2.

set -euo pipefail

# === Bash version guard (RESEARCH.md Pitfall 8) ===
# `wait -n` (used by the multi-process variant) requires bash >= 4.3.
# Fail fast with a clear message; do not silently degrade.
if (( BASH_VERSINFO[0] < 4 )) || { (( BASH_VERSINFO[0] == 4 )) && (( BASH_VERSINFO[1] < 3 )); }; then
  echo "[pivota] bash 4.3+ required for 'wait -n'; found ${BASH_VERSION}" >&2
  exit 127
fi

# === D-11.4: tee stdout/stderr to /tmp/pivota-dev.log AND pass through ===
mkdir -p /tmp
exec > >(tee -a /tmp/pivota-dev.log) 2>&1
echo "[pivota] $(date -Iseconds) start-dev.sh begin (catalog: agent/react-vite+express)"

# === D-11.1 + D-11.2: per-stack 0.0.0.0 binding + host allowlist relaxation ===
export HOST=0.0.0.0
# NOTE: Vite does NOT honor HOST as a server bind var; it is set here only for
# downstream tooling. The actual Vite bind comes from the --host 0.0.0.0 CLI
# flag in the Vite process invocation below.
# Express uses PORT for its bind address — set via inline env in process block.

# === D-11.3: .env.example -> .env transitional copy (until Phase 38) ===
if [[ ! -f .env && -f .env.example ]]; then
  echo "[pivota] copying .env.example -> .env (Phase 38 will replace this hack)"
  cp .env.example .env
fi

# === Optional pre-exec snippet: write vite.config.pivota.ts for host allowlist ===
if [[ -f vite.config.ts && ! -f vite.config.pivota.ts ]]; then
  if ! grep -q "allowedHosts" vite.config.ts 2>/dev/null; then
    cat > vite.config.pivota.ts <<'EOF'
// Auto-generated by pivota init-dev-server. Extends user's vite.config.ts at runtime
// to set server.allowedHosts = true (sandbox preview embedding) and host=true (so
// the dev server binds 0.0.0.0). Remove this file if you set allowedHosts yourself.
import { defineConfig, mergeConfig } from 'vite';
import userConfig from './vite.config';
export default defineConfig((env) => mergeConfig(
  typeof userConfig === 'function' ? userConfig(env) : userConfig,
  { server: { host: true, allowedHosts: true, strictPort: true } }
));
EOF
    echo "[pivota] wrote vite.config.pivota.ts (allowedHosts overlay)"
  fi
fi

# === D-12: idempotent install via lockfile hash + presence check ===
SENTINEL="/tmp/pivota-setup-sentinel"
LOCK_FILE_PATH="package-lock.json"
INSTALL_PRESENCE_CHECK="node_modules"
INSTALL_CMD='npm ci || npm install'

run_install() {
  echo "[pivota] running install: $INSTALL_CMD"
  bash -c "$INSTALL_CMD"
}

if [[ -n "$LOCK_FILE_PATH" && -f "$LOCK_FILE_PATH" ]]; then
  CURRENT_HASH=$(sha256sum "$LOCK_FILE_PATH" | cut -d' ' -f1)
  PREVIOUS_HASH=$(cat "$SENTINEL" 2>/dev/null || echo "")

  PRESENCE_OK=1
  if [[ -n "$INSTALL_PRESENCE_CHECK" && ! -e "$INSTALL_PRESENCE_CHECK" ]]; then
    PRESENCE_OK=0
  fi

  if [[ "$CURRENT_HASH" == "$PREVIOUS_HASH" && "$PRESENCE_OK" == "1" ]]; then
    echo "[pivota] lockfile unchanged AND install output present; skipping install"
  else
    if [[ "$PRESENCE_OK" == "0" ]]; then
      echo "[pivota] install output ($INSTALL_PRESENCE_CHECK) missing; install required"
    else
      echo "[pivota] lockfile changed (or first boot); install required"
    fi
    run_install
    echo "$CURRENT_HASH" > "$SENTINEL"
  fi
elif [[ -n "$INSTALL_CMD" ]]; then
  if [[ ! -f "$SENTINEL" ]]; then
    run_install
    touch "$SENTINEL"
  fi
fi

# === Defense-in-depth bash version guard for multi-process (RESEARCH.md Pitfall 8) ===
if (( BASH_VERSINFO[0] < 4 )) || { (( BASH_VERSINFO[0] == 4 )) && (( BASH_VERSINFO[1] < 3 )); }; then
  echo "[pivota] multi-process block requires bash 4.3+ for wait -n; found ${BASH_VERSION}" >&2
  exit 127
fi

# === Port cleanup: kill any lingering process on port 3000 before binding ===
# Prevents EADDRINUSE when the script is restarted with a previous instance's
# TIME_WAIT socket or a stale backend still running.
_free_port() {
  local port="$1"
  local pid
  pid=$(grep ":$(printf '%04X' "$port") " /proc/net/tcp6 /proc/net/tcp 2>/dev/null \
    | awk '$4 == "0A" {print $10}' \
    | head -1)
  if [[ -n "$pid" ]]; then
    echo "[pivota] killing existing listener on port $port (inode-based; checking pids)"
  fi
  # Kill any tsx/node process that might hold port 3000
  pkill -f "tsx server" 2>/dev/null || true
  pkill -f "node.*server" 2>/dev/null || true
  sleep 1
}
_free_port 3000

# === Multi-process: Express backend + Vite frontend ===
shutdown() {
  echo "[pivota] shutting down children"
  kill -TERM "${PIDS[@]}" 2>/dev/null || true
  # Brief grace, then SIGKILL stragglers (RESEARCH.md Pitfall 3: npm SIGTERM)
  sleep 2
  kill -KILL "${PIDS[@]}" 2>/dev/null || true
  wait
}
trap shutdown SIGTERM SIGINT EXIT

declare -a PIDS=()

# Process 1: Express backend on port 3000
(
  cd '.' \
    && export PORT=3000 \
    && exec bash -c 'npx tsx server.ts'
) 2>&1 | sed 's/^/[backend] /' &
PIDS+=($!)

# Process 2: Vite frontend on port 5173, bound to 0.0.0.0 with allowedHosts overlay
# NOTE: Run vite directly (not via 'npm run dev') to avoid invoking concurrently
# which would launch a second tsx server.ts and conflict with Process 1 on port 3000.
(
  cd '.' \
    && : \
    && exec bash -c 'npx vite --config vite.config.pivota.ts --host 0.0.0.0 --strictPort 2>/dev/null || npx vite --host 0.0.0.0 --strictPort'
) 2>&1 | sed 's/^/[frontend] /' &
PIDS+=($!)

echo "[pivota] started backend (pid ${PIDS[0]}) and frontend (pid ${PIDS[1]})"

# Wait for ANY child to exit; if one dies, the trap tears down siblings.
wait -n
EXIT_CODE=$?
shutdown
exit "$EXIT_CODE"

# === END PIVOTA PREAMBLE ===
# Below this marker, projects may add custom shutdown / setup logic.
# This region is PRESERVED across regenerations.
